---
title: "Course Project - Getting and Cleaning Data"
author: "David Eborall"
date: "21 September 2014"
output: html_document
---
##Instructions##

1. Git clone this repository. 
2. Run the run_analysis.R from the root folder of the repository
3. The script will generate an output of project_tidy.txt in the root folder

##Data Source##

Dataset description: <http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones#>

Download url: <https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip>

NOTE: The R script will download the dataset and unzip git. Therefore, start from the scipt before using the above links. 

###Dependencies###
- library(plyr) #for dplyr
- library(stringr) # String functions
- library(reshape2)

##R Script Outline##

- Require dependencies
- Check data paths are correct and whether datasets exists. If not, download data sets and unzip in chosen directory
- Read training and test files and append training dataset to test data set
- Add subjects and activities using left join
- Make labels more descriptive
- Extract measurements into a tidy dataset format
- cast activities as x-dimensions
- output file into a tidy data set called project_tidy.txt


Email: dave.eborall[at]gmail.com


